//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolluskRecognition.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MolluskRecognition.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить признак.
        /// </summary>
        public static string AddFeatureButtonText {
            get {
                return ResourceManager.GetString("AddFeatureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление нового признака.
        /// </summary>
        public static string AddFeaturePopupTitle {
            get {
                return ResourceManager.GetString("AddFeaturePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление нового экземпляра.
        /// </summary>
        public static string AddNewElementTitle {
            get {
                return ResourceManager.GetString("AddNewElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подпризнак.
        /// </summary>
        public static string AddSubFeatureButtonText {
            get {
                return ResourceManager.GetString("AddSubFeatureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст:.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to угол альфа (угол между замочным краем и главной диагональю):.
        /// </summary>
        public static string AlfaLabel {
            get {
                return ResourceManager.GetString("AlfaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор:.
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задний конец:.
        /// </summary>
        public static string BackEndLabel {
            get {
                return ResourceManager.GetString("BackEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to угол бетта (верхний дорзальный угол, верхнезадний):.
        /// </summary>
        public static string BettaLabel {
            get {
                return ResourceManager.GetString("BettaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брюшной край:.
        /// </summary>
        public static string BrushnoyEdgeLabel {
            get {
                return ResourceManager.GetString("BrushnoyEdgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог НДМ.
        /// </summary>
        public static string CatalogButtonText {
            get {
                return ResourceManager.GetString("CatalogButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие характеристики.
        /// </summary>
        public static string CommonHaracteristicsHeader {
            get {
                return ResourceManager.GetString("CommonHaracteristicsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение:.
        /// </summary>
        public static string CompareLabel {
            get {
                return ResourceManager.GetString("CompareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрезы.
        /// </summary>
        public static string CutsHeader {
            get {
                return ResourceManager.GetString("CutsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробное описание.
        /// </summary>
        public static string DetailDescriptionHeader {
            get {
                return ResourceManager.GetString("DetailDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D (длина диагонали), мм.:.
        /// </summary>
        public static string DLabel {
            get {
                return ResourceManager.GetString("DLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        public static string FeatureNameLabel {
            get {
                return ResourceManager.GetString("FeatureNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передний конец:.
        /// </summary>
        public static string FrontEndLabel {
            get {
                return ResourceManager.GetString("FrontEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H (высота раковины), мм.:.
        /// </summary>
        public static string HLabel {
            get {
                return ResourceManager.GetString("HLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальная раковина:.
        /// </summary>
        public static string InitialShellLabel {
            get {
                return ResourceManager.GetString("InitialShellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип начальной раковины.
        /// </summary>
        public static string InitialShellTypeLabel {
            get {
                return ResourceManager.GetString("InitialShellTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l1 (длина малого плеча), мм.:.
        /// </summary>
        public static string l1Label {
            get {
                return ResourceManager.GetString("l1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l2 (длина большого плеча), мм.:.
        /// </summary>
        public static string l2Label {
            get {
                return ResourceManager.GetString("l2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L (длина раковины), мм.:.
        /// </summary>
        public static string LLabel {
            get {
                return ResourceManager.GetString("LLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить изображение.
        /// </summary>
        public static string LoadButtonText {
            get {
                return ResourceManager.GetString("LoadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение.
        /// </summary>
        public static string LocationHeader {
            get {
                return ResourceManager.GetString("LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l (длина замочного края), мм.:.
        /// </summary>
        public static string lzLabel {
            get {
                return ResourceManager.GetString("lzLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карты.
        /// </summary>
        public static string MapButtonText {
            get {
                return ResourceManager.GetString("MapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № коллекции:.
        /// </summary>
        public static string OrderNumberCollectionLabel {
            get {
                return ResourceManager.GetString("OrderNumberCollectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заполнение физических параметров. Размеры.
        /// </summary>
        public static string PhysicalParametersHeader {
            get {
                return ResourceManager.GetString("PhysicalParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Положение в коллекции.
        /// </summary>
        public static string PositionInCollectionHeader {
            get {
                return ResourceManager.GetString("PositionInCollectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № образца:.
        /// </summary>
        public static string SampleOrderNumber {
            get {
                return ResourceManager.GetString("SampleOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографии экземпляров:.
        /// </summary>
        public static string SamplesHeader {
            get {
                return ResourceManager.GetString("SamplesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скульптура:.
        /// </summary>
        public static string Sculpture {
            get {
                return ResourceManager.GetString("Sculpture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string SearchWindowTitle {
            get {
                return ResourceManager.GetString("SearchWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выборка.
        /// </summary>
        public static string SelectedItemsText {
            get {
                return ResourceManager.GetString("SelectedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раковина:.
        /// </summary>
        public static string ShellLabel {
            get {
                return ResourceManager.GetString("ShellLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор рода и вида.
        /// </summary>
        public static string SpeciesAndGenusHeader {
            get {
                return ResourceManager.GetString("SpeciesAndGenusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макушки:.
        /// </summary>
        public static string SpotsLabel {
            get {
                return ResourceManager.GetString("SpotsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор режима работы.
        /// </summary>
        public static string StartWindowTitle {
            get {
                return ResourceManager.GetString("StartWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синонимика:.
        /// </summary>
        public static string SynonymyLabel {
            get {
                return ResourceManager.GetString("SynonymyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год:.
        /// </summary>
        public static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замочный край:.
        /// </summary>
        public static string ZamochniyEdge {
            get {
                return ResourceManager.GetString("ZamochniyEdge", resourceCulture);
            }
        }
    }
}
